config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    root 'static_pages#root'
    resources :users
    resources :articles do
      resources :comments
    end
  end
  root 'static_pages#root'
  get 'about', to: 'static_pages#about'
  resources :users
  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}
  validates :user_id, presence: true
  accepts_nested_attributes_for :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  enum status: [:published, :unpublished, :not_set]
  validates :comment, presence: true, length: {minimum: 1, maximum: 300}
  belongs_to :article
  belongs_to :user


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!
  before_action :authorize_user
  after_action :verify_authorized

  def new
    @article = Article.new
  end
  def create
    #render plain: current_user.id
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:success] = "Article was successfully created!"
      redirect_to admin_articles_path
    else
      render 'new'
    end
  end
  def show
    @comment = Comment.new
    @comments = @article.comments
  end
  def edit

  end
  def update
    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to admin_articles_path
    else
      flash[:success] = "Article was not updated"
      render 'edit'
    end
  end
  def index
    @article = Article.all
  end
  def destroy
    @article.destroy
    flash[:success] = "Article was deleted"
    redirect_to admin_articles_path
  end
  def set_article
    @article = Article.find(params[:id])
  end
  def authorize_user
    authorize [:admin, Article]
  end
  private
  def article_params
    params.require(:article).permit(:title,:description)
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user
  after_action :verify_authorized
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.status = "unpublished"

    if @comment.save
      flash[:success] = "Comment was added!"
      redirect_to admin_article_path(@article)

    else
      flash[:success] = "Comment was not added"
      redirect_to admin_article_path(@article)
    end
  end
  def update
    @article = Article.find(params[:id])
    @comment = Comment.find(params[:article_id])
    if @comment.status == "published"
      @comment.update(status: "unpublished")
      flash[:success] = "Comment was unpublished"
      redirect_to request.referrer
    else
      @comment.update(status: "published")
      flash[:success] = "Comment was published"
      redirect_to request.referrer || admin_root_path
    end
  end
  def edit
  end
  def destroy
    @comment = Comment.find(params[:article_id])
    @comment.destroy
    flash[:success] = "Comment was deleted"
    redirect_to request.referrer || admin_root_path
  end
  def authorize_user
    authorize [:admin, Comment]
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/admin/static_pages_controller.rb
class Admin::StaticPagesController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized
  def root
    authorize User
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_user
  after_action :verify_authorized
  before_action :set_user, only: [:edit, :update, :show, :destroy]

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to admin_users_path
    else
      flash[:success] = "User was not updated"
      render 'edit'
    end
  end
  def edit
  end
  def show
  end
  def destroy
    @user.destroy
    flash[:success] = "User was deleted"
    redirect_to admin_users_path
  end
  def index
    @user = User.all
  end
  def set_user
    @user = User.find(params[:id])
  end
  def authorize_user
    authorize [:admin, User]
  end
  private
  def user_params
    params.require(:user).permit(:username,:email,:password,:password_confirmation,:role)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception

  private

    def user_not_authorized
      flash[:alert] = "Access denied."
      redirect_to (request.referrer || root_path)
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,]
  before_action :authenticate_user!
  after_action :verify_authorized
  def new
    if current_user
       @article = Article.new
    else
      redirect_to articles_path
    end
  end
  def show
    authorize Article
    @comments = @article.comments.all
    @comment = @article.comments.new

  end
  def index
    authorize Article
    @article = Article.all
  end
  def set_article
    @article = Article.find(params[:id])
  end
  private
    def article_params
      params.require(:article).permit(:title,:description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article, only: [:create, :update]
  before_action :authenticate_user!
  after_action :verify_authorized
  def create
   authorize Comment
   @comment = @article.comments.create(comment_params)
   @comment.user_id = current_user.id
   @comment.status = "unpublished"

   if @comment.save
     flash[:success] = "Udało się dodać komentarz! Poczekaj na zaakceptowanie go przez administratora"
     redirect_to @article
   end

  end
  def set_article
    @article = Article.find(params[:article_id])
  end
  private
  def comment_params
    params.require(:comment).permit(:comment)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:update, :show, :destroy]
  after_action :verify_authorized
  def new
    @user = User.new
  end
  def index
    @users = User.all
    authorize User
  end

  def show
    authorize @user
  end

  private

    def secure_params
      params.require(:user).permit(:role)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@article], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>
        </div>
        <div class="col-sm-6">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/admin/articles/index.html.erb
<h1 align="center">Manage Articles</h1>
<%= link_to 'Add Article', new_admin_article_path %>
<table class = "table table-striped table-hover">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th colspan="2"> </th>
      </tr>
    </thead>
    <tbody>
    <% @article.each do |article| %>
    <tr>
      <td> <%= article.title %></td>
      <td> <%= article.description %></td>
      <td> <%= link_to 'Show', admin_article_path(article)%></td>
      <td> <%= link_to 'Edit', edit_admin_article_path(article) %></td>
      <td> <%= link_to 'Destroy', admin_article_path(article), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>
    </tbody>
  </table>

app/views/admin/articles/new.html.erb
  <h1>Create an article</h1>
  <%= render 'form' %>

app/views/admin/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<h4 class="center"><strong>Description:</strong></h4>
<hr>
<h5 class="center"><%= @article.description%></h5>
  <ul>
    <%= render partial: 'admin/comments/form'%>
    <%= render partial: 'admin/comments/comment'%>
  </ul>


</div>

app/views/admin/comments/_comment.html.erb
<table class = "table table-striped table-hover">
  <thead>
  <tr>
    <th>Comment</th>
    <th>Status</th>

    <th colspan="2"> </th>
  </tr>
  </thead>
  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td> <%= comment.comment %></td>
      <td> <%= comment.status %></td>
      <td> <%= link_to 'Destroy', admin_article_comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <td><% if comment.status ==  "published" %>
          <%= link_to "Unpublish", admin_article_comment_path(comment), method: :put, data: { confirm: "You sure?"} %>
        <% end %>
        <% if comment.status ==  "unpublished" %>
          <%= link_to "Publish", admin_article_comment_path(comment), method: :put, data: {confirm: "You sure?"}%>
        <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/comments/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@article,@comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :comment %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :comment, rows: 5, class: "form-control", placeholder: "Comment" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/dashboard/index.html.erb
<h1>Administration</h1>

<h2> This is admin panel</h2>

app/views/admin/dashboard/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li><%= link_to gravatar_for(@article.user), admin_user_path(@article.user) %></li>
          <li class="article-title"><%= link_to @article.user.username, admin_user_path(@article.user) %></li>
          <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <div class="article-actions">
    <% if current_user && current_user.id == @article.user_id %>
      <%= link_to "Edit", edit_admin_article_path(@article), class: "btn btn-xs btn-primary" %>
      <%= link_to "Delete", admin_article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
    <% end %>
  </div>
  <h4 class="left"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <ul>
    <%= render partial: 'comments/form'%>
    <%= render partial: 'comments/comment'%>
  </ul>


</div>

app/views/admin/pages/about.html.erb
<h1>About Blog</h1>

<%= link_to 'Home', root_path %>

app/views/admin/pages/index.html.erb
<h1> Welcome to Blog </h1>

<%= link_to 'About', about_path %>

app/views/admin/static_pages/about.html.erb
<h1>About Blog</h1>

app/views/admin/static_pages/root.html.erb
<% if user_signed_in? && current_user.role == 'admin' %>
  <h1> Admin Panel</h1>
<% end %>
<% if (user_signed_in? && current_user.role != 'admin') || !user_signed_in? %>
  <h1> Home Page</h1>
<% end %>

app/views/admin/users/_form.html.erb
<%= render 'shared/errors', obj: @user %><div class="row">
  <div class="col-xs-12">
    <%= form_for([:admin,@user], :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :username %>
        </div>
        <div class="col-sm-7">
          <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :email %>
        </div>
        <div class="col-sm-7">
          <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password %>
        </div>
        <div class="col-sm-7">
          <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :password_confirmation %>
        </div>
        <div class="col-sm-7">
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm password" %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :role %>
        </div>
        <div class="col-sm-7">
          <%= f.select :role, [['Admin','admin'],['User','user']], {class: "form-control"} %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-7">
          <%= f.submit(@user.new_record?  ? "Sign up" : "Update account", class: 'btn btn-primary btn-large') %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-2">
      [ <%= link_to 'Cancel request and Return to Articles Listing', articles_path %> ]
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<h1 align="center">Edit User Account</h1>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1 align="center">Manage Users</h1>
<table class = "table table-striped table-hover">
  <thead>
  <tr>
    <th>Email</th>
    <th>Role</th>

    <th colspan="2"> </th>
  </tr>
  </thead>
  <tbody>
  <% @user.each do |user| %>
    <tr>
      <td> <%= user.email %></td>
      <td> <%= user.role %></td>
      <td> <%= link_to 'Show', admin_user_path(user)%></td>
      <td> <%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td> <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1 align="center">Signup</h1>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h1 align="center">Welcome to <%= @user.email %>'s page</h1>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1><% @article.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <div class = "article-meta-details">
          <small>Created by: <%= article.user.username if article.user  %>,
            <%= time_ago_in_words(article.created_at) %> ago,
            last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <% if current_user && current_user.id == article.user_id %>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @article.user %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
        </div>
      </div>
    </ul>
  <% end %>
  <div class="article-actions">

  </div>
  <h4 class="left"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@article.description) %>
  <ul>
    <%= render partial: 'comments/form'%>
    <%= render partial: 'comments/comment'%>
  </ul>


</div>

app/views/comments/_comment.html.erb
<% @comments.each do |comment|%>
  <% if comment.status == "published"  %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to comment.user.username, user_path(comment.user_id) %>
        </div>
        <div class="article-body">
          <%= truncate(comment.comment, length: 100) %>
        </div>
      </div>
    </div>
  </div>
    <% end %>
<% end %>

app/views/comments/_form.html.erb
<% if current_user %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for([@article,@comment], :html => {class: "form-horizontal", role: "form"}) do |f| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :comment %>
        </div>
        <div class="col-sm-6">
          <%= f.text_area :comment, rows: 5, class: "form-control", placeholder: "Comment" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-6">
          <%= f.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% end %>

app/views/shared/_article.html.erb
<% obj.each do |article|%>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
            <small>Created by: <%= article.user.username if article.user %>,
              <%= time_ago_in_words(article.created_at) %> ago,
              last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg|%>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div align="center">
  <h1 align="center">All Users</h1><% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <li class="article-title"><%= link_to user.username, user_path(user) %></li>
          <li><small><%=user.email %></small></li>
          <li><small><%= pluralize(user.articles.count, "article") if user.articles %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'user' %>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>